// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core from "@material-ui/core";
import * as JsxRuntime from "react/jsx-runtime";

function Button(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Core.Button, {
                      children: "Example Button",
                      className: "primary-button",
                      color: "Primary",
                      variant: "Contained"
                    }),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx(Core.Button, {
                      children: "Example Button",
                      className: "secondary-button",
                      variant: "Outlined"
                    })
              ]
            });
}

var make = Button;

export {
  make ,
}
/* @material-ui/core Not a pure module */
