// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Button from "./components/Button.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsx(JsxRuntime.Fragment, {
              children: Caml_option.some(JsxRuntime.jsx(Button.make, {}))
            });
}

var make = App;

export {
  make ,
}
/* Button Not a pure module */
